image: gitpod/workspace-full

tasks:
  - init: docker-compose up -d
    name: Start SaaS Stack

ports:
  - port: 80
    onOpen: open-preview
  - port: 443
    onOpen: open-preview
  - port: 5678
    onOpen: ignore
