image: gitpod/workspace-full

tasks:
  - name: Start SaaS Stack
    init: docker-compose up -d
    command: docker-compose logs -f

ports:
  - port: 80
    onOpen: open-preview
  - port: 443
    onOpen: open-preview
  - port: 5678
    onOpen: ignore
